url: https://heydavid-dev.github.io
base1
# Site settings
header_title: Howdy Cowboy
header_subtitle: To infinity and beyond! !@#$@!!@

title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      2    - title: facebook
      3    - title: stack-overflow
      4
- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      5    - title: facebook
      6    - title: linkedin
      7
- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      8    - title: facebook
      9    - title: google-plus
      10
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    11  - title: facebook
    12  - title: stack-overflow
    13  - title: bitbucket 
    14  - title: github
    15
# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
